In [7]:
import pandas as pd
df_excel = pd.read_excel('/content/sangeeta.xlsx')
print(df_excel)

    Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0          NaN         NaN         NaN         NaN        NaN        NaN
1          NaN         NaN         NaN         NaN        NaN        NaN
2          NaN         NaN         NaN         NaN    REF NO.   EMP_NAME
3          NaN         NaN         NaN         NaN       1002      ANMOL
4          NaN         NaN         NaN         NaN       1003        ANU
5          NaN         NaN         NaN         NaN       1004       ASHA
6          NaN         NaN         NaN         NaN       1005      DISHA
7          NaN         NaN         NaN         NaN       1006      KAMAL
8          NaN         NaN         NaN         NaN       1001      NEERU
9          NaN         NaN         NaN         NaN       1007      NITIN
10         NaN         NaN         NaN         NaN       1008      RAHUL
11         NaN         NaN         NaN         NaN       1009      REKHA
12         NaN         NaN         NaN         NaN       1010     SHWETA

   Unnamed: 6 Unnamed: 7   Unnamed: 8    Unnamed: 9 Unnamed: 10
0         NaN        NaN          NaN           NaN         NaN
1         NaN        NaN          NaN           NaN         NaN
2         FAN    HEATHER  TOTAL SALES  FIXED SALARY       BONUS
3         123        233          356         14000           0
4         780        782         1562         12000        2400
5         789        129          918         12000         600
6         789        678         1467         19000        1900
7         540        350          890         17000         850
8         178        456          634         12000         600
9         789        345         1134         12000        1200
10        345        678         1023         10000        1000
11        900        127         1027         13000        1300
12        222        789         1011         12900        1290